(() => {
  const style = document.createElement('style');
  style.textContent = `
    .poi-skeleton{overflow:hidden}.skeleton-block,.skeleton-line{position:relative;background:var(--surface-2,#222);overflow:hidden}.skeleton-block{height:100%;min-height:180px}.skeleton-line{height:14px;border-radius:8px;margin:10px 0;width:75%}.skeleton-line.wide{width:92%}.skeleton-line.short{width:45%}.skeleton-block:after,.skeleton-line:after{content:"";position:absolute;inset:0;transform:translateX(-100%);background:linear-gradient(90deg,transparent,rgba(255,255,255,.12),transparent);animation:jarvisShimmer 1.2s infinite}@keyframes jarvisShimmer{100%{transform:translateX(100%)}}
    .jarvis-modal{position:fixed;inset:0;z-index:1000;background:rgba(0,0,0,.62);display:flex;align-items:flex-end;justify-content:center;padding:12px}.jarvis-modal-card{width:min(760px,100%);max-height:88vh;overflow:auto;background:var(--bg,#101014);border-radius:24px;padding:18px;box-shadow:0 12px 50px rgba(0,0,0,.45)}
    .jarvis-detail-image{width:100%;max-height:360px;object-fit:cover;border-radius:18px;margin-bottom:14px}.jarvis-detail-placeholder{display:grid;place-items:center;min-height:180px;font-size:42px;background:var(--surface-2,#222);border-radius:18px}.jarvis-close{float:right;border:0;background:none;color:inherit;font-size:30px}.jarvis-detail-title{font-size:24px;font-weight:700;margin:8px 0 14px}.jarvis-detail-meta{color:var(--muted);line-height:1.6}.jarvis-modal-btn{width:100%;padding:13px;margin-top:9px;border:0;border-radius:13px;background:var(--surface-2,#25252b);color:inherit;font-weight:600}.jarvis-modal-btn.primary{background:var(--accent,#fff);color:#111}.jarvis-route-url{padding:12px;margin-top:12px;border-radius:12px;background:var(--surface-2,#222);word-break:break-all;user-select:text;-webkit-user-select:text;font-size:12px}.jarvis-route-text{white-space:pre-line;line-height:1.55}.jarvis-route-actions{display:grid;gap:4px}
  `;
  document.head.appendChild(style);

  const openModal = html => { const old=document.getElementById('jarvis-modal'); if(old) old.remove(); const el=document.createElement('div'); el.id='jarvis-modal'; el.className='jarvis-modal'; el.innerHTML=`<div class="jarvis-modal-card">${html}</div>`; el.onclick=e=>{if(e.target===el)el.remove()}; document.body.appendChild(el); };
  window.closeJarvisModal=()=>document.getElementById('jarvis-modal')?.remove();

  window.openPoiDetail=async id=>{ openModal('<div class="jarvis-detail-title">Загрузка…</div>'+`<div class="poi-skeleton"><div class="skeleton-block" style="height:220px"></div><div class="skeleton-line wide"></div><div class="skeleton-line"></div></div>`); try{const place=await apiFetch(`/pois/${encodeURIComponent(id)}`); const image=place.images?.large||place.images?.medium||place.images?.thumb||place.image_url||place.photo?.local_url_large||place.photo?.local_url_medium; openModal(`<button class="jarvis-close" onclick="closeJarvisModal()">×</button>${image?`<img class="jarvis-detail-image" src="${escapeAttr(image)}" onerror="this.outerHTML='<div class=\'jarvis-detail-placeholder\'>🏛️</div>'">`:'<div class="jarvis-detail-placeholder">🏛️</div>'}<div class="jarvis-detail-title">${escapeHtml(place.name||'Место')}</div><div class="jarvis-detail-meta">📍 ${escapeHtml(place.city||'')}${place.address?`<br>🏠 ${escapeHtml(place.address)}`:''}${place.category?`<br>🏛 ${escapeHtml(place.category)}`:''}${place.hours?`<br>🕒 ${escapeHtml(place.hours)}`:''}</div><button class="jarvis-modal-btn" onclick="toggleFav('${escapeAttr(String(place.id))}');closeJarvisModal()">♡ Добавить в Favorites</button><button class="jarvis-modal-btn primary" onclick="toggleRoute('${escapeAttr(String(place.id))}');closeJarvisModal()">＋ Добавить в маршрут</button>`); }catch(e){openModal(`<div class="jarvis-detail-title">Не удалось загрузить</div><p>${escapeHtml(e.message||'Ошибка')}</p>`)} };

  window.copyRouteLink=async url=>{ if(!url)return toast('Ссылка маршрута отсутствует'); try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(url);else throw new Error();toast('Ссылка скопирована');}catch(_){const ta=document.createElement('textarea');ta.value=url;ta.setAttribute('readonly','');ta.style.position='fixed';ta.style.left='-9999px';document.body.appendChild(ta);ta.select();ta.setSelectionRange(0,999999);let ok=false;try{ok=document.execCommand('copy')}catch(e){}ta.remove();if(ok)toast('Ссылка скопирована');else toast('Выделите ссылку вручную')}};
  window.openRouteLink=url=>{if(!url)return toast('Ссылка маршрута отсутствует');try{if(tg?.openLink){tg.openLink(url,{try_instant_view:false});return}}catch(_){}try{window.open(url,'_blank','noopener,noreferrer')}catch(_){location.href=url}};
  window.showRouteModal=data=>{const names=(S.route||[]).map((p,i)=>`${i+1}. ${p.name}`).join('\n');const url=data?.google_maps_url||'';openModal(`<button class="jarvis-close" onclick="closeJarvisModal()">×</button><div class="jarvis-detail-title">🗺 Маршрут готов</div><div class="jarvis-route-text">${escapeHtml(names)}</div>${data?.total_distance_km!=null?`<p>Расстояние: ${escapeHtml(String(data.total_distance_km))} км</p>`:''}<div class="jarvis-route-url" id="route-url">${escapeHtml(url)}</div><button class="jarvis-modal-btn primary" onclick="openRouteLink(${JSON.stringify(url)})">Открыть Google Maps</button><button class="jarvis-modal-btn" onclick="copyRouteLink(${JSON.stringify(url)})">Копировать ссылку</button>`)};

  const oldBuildRoute=window.buildRoute; window.buildRoute=async()=>{if(typeof oldBuildRoute!=='function')return; try{await oldBuildRoute()}catch(e){toast(e.message||'Ошибка маршрута')}};
})();