(() => {
  const PAGE_SIZE=8; const pageCache=new Map(); let currentPage=0,hasNextPage=false,loading=false,queryKey='';
  const loadingMarkup=()=>`<div class="jarvis-loading" aria-live="polite"><div class="jarvis-spinner"></div><div class="jarvis-loading-title">JARVIS ищет места…</div><div class="jarvis-skeleton-feed">${Array.from({length:8},()=>'<div class="poi-skeleton"><div class="poi-skeleton-img"></div><div class="poi-skeleton-body"><div class="poi-skeleton-line wide"></div><div class="poi-skeleton-line"></div><div class="poi-skeleton-line short"></div></div></div>').join('')}</div></div>`;
  const key=()=>JSON.stringify({region:S.region,city:S.city,tags:[...S.tags].sort()});
  function styles(){if(document.getElementById('jarvis-ux-fixes-style'))return;const s=document.createElement('style');s.id='jarvis-ux-fixes-style';s.textContent=`.jarvis-loading{text-align:center;padding:18px 0}.jarvis-spinner{width:28px;height:28px;margin:4px auto 10px;border:3px solid var(--border);border-top-color:var(--blue);border-radius:50%;animation:jarvis-spin .8s linear infinite}@keyframes jarvis-spin{to{transform:rotate(360deg)}}.jarvis-loading-title{color:var(--muted);font-size:13px;margin-bottom:14px}.jarvis-skeleton-feed{display:grid;gap:12px}.poi-skeleton{display:grid;grid-template-columns:38% 1fr;min-height:148px;border:1px solid var(--border);border-radius:18px;background:var(--panel);overflow:hidden}.poi-skeleton-img,.poi-skeleton-line{background:linear-gradient(90deg,var(--panel-2),var(--input),var(--panel-2));background-size:200% 100%;animation:jarvis-shimmer 1.3s infinite}.poi-skeleton-body{padding:15px}.poi-skeleton-line{height:11px;border-radius:8px;margin-bottom:10px;width:72%}.poi-skeleton-line.wide{width:92%;height:16px}.poi-skeleton-line.short{width:48%}@keyframes jarvis-shimmer{0%{background-position:200%}100%{background-position:-200%}}`;document.head.appendChild(s)}
  function render(){const f=document.getElementById('feed'),b=document.getElementById('poi-pagination');if(!f)return;const places=S.filtered||[];f.innerHTML=places.length?places.map(p=>{const id=String(p.id),im=p.images?.medium||p.images?.thumb||p.image_url||p.images?.original,fav=S.favs.has(id),rt=S.route.some(x=>String(x.id)===id);return `<div class="poi-card" role="button" tabindex="0" onclick="openPoiDetail('${escapeAttr(id)}')"><div class="poi-img">${im?`<img src="${escapeAttr(im)}" alt="${escapeAttr(p.name)}" loading="lazy" onerror="this.parentElement.innerHTML='<div class=\'jarvis-detail-placeholder\'>🏛️</div>'">`:'<div class="jarvis-detail-placeholder">🏛️</div>'}</div><div class="poi-body"><div class="poi-name">${escapeHtml(p.name)}</div><div class="poi-loc">📍 ${escapeHtml(p.city||'')}</div><div class="poi-actions"><button class="poi-act ${fav?'active':''}" onclick="event.stopPropagation();toggleFav('${escapeAttr(id)}')">${fav?'❤️':'♡'} Favorite</button><button class="poi-act ${rt?'active':''}" onclick="event.stopPropagation();toggleRoute('${escapeAttr(id)}')">${rt?'✓':'＋'} Route</button></div></div></div>`}).join(''):'<div style="text-align:center;padding:50px;color:var(--muted)">Ничего не найдено</div>';if(b)b.innerHTML=(places.length||hasNextPage)?`<button class="poi-page-btn" ${currentPage===0||loading?'disabled':''} onclick="loadPoiPage(${currentPage-1})">←</button><span class="poi-page-label">Страница ${currentPage+1}</span><button class="poi-page-btn" ${!hasNextPage||loading?'disabled':''} onclick="loadPoiPage(${currentPage+1})">→</button>`:''}
  window.loadPoiPage=async p=>{if(p<0||loading)return;const k=key();if(k!==queryKey){pageCache.clear();queryKey=k;currentPage=0;hasNextPage=false}const c=pageCache.get(p);if(c){currentPage=p;S.filtered=c.places;hasNextPage=c.hasNext;render();document.getElementById('cards')?.scrollTo({top:0,behavior:'smooth'});return}loading=true;const f=document.getElementById('feed');if(f)f.innerHTML=loadingMarkup();try{const d=await apiFetch('/pois/query',{method:'POST',body:JSON.stringify({region:S.region,city:S.city,tags:[...S.tags],limit:PAGE_SIZE+1,offset:p*PAGE_SIZE})});const pois=Array.isArray(d?.pois)?d.pois:[],c2={places:pois.slice(0,PAGE_SIZE),hasNext:pois.length>PAGE_SIZE};if(k!==queryKey)return;pageCache.set(p,c2);currentPage=p;S.filtered=c2.places;hasNextPage=c2.hasNext;render();document.getElementById('cards')?.scrollTo({top:0,behavior:'smooth'})}catch(e){if(f)f.innerHTML='<div style="text-align:center;padding:50px;color:var(--muted)">Не удалось загрузить страницу.<br>Попробуйте ещё раз.</div>';toast(e.message||'Ошибка загрузки')}finally{loading=false;render()}};
  window.loadCards=async()=>{if(!S.region||!S.city)return toast('Сначала выберите регион и город');if(!S.tags.size)return toast('Выберите хотя бы одну категорию');styles();go('cards');pageCache.clear();queryKey=key();currentPage=0;hasNextPage=false;S.filtered=[];const f=document.getElementById('feed');if(f)f.innerHTML=loadingMarkup();const t=document.getElementById('cards-title');if(t)t.textContent=S.city;await window.loadPoiPage(0)};
  window.renderFeed=render;
  window.copyRouteLink=async url=>{const v=String(url||'');if(!v)return toast('Ссылка на маршрут отсутствует');try{await navigator.clipboard.writeText(v);toast('Ссылка скопирована');return}catch(_){}try{const a=document.createElement('textarea');a.value=v;a.style.position='fixed';a.style.opacity='0';document.body.appendChild(a);a.focus();a.select();const ok=document.execCommand('copy');a.remove();if(ok)return toast('Ссылка скопирована')}catch(_){}toast('Не удалось скопировать — выделите ссылку вручную')};
  window.openRouteLink=url=>{const v=String(url||'');if(!v)return toast('Ссылка отсутствует');try{window.Telegram?.WebApp?.openLink?.(v,{try_instant_view:false});return}catch(_){}try{window.open(v,'_blank','noopener,noreferrer')}catch(_){location.href=v}};
  const route=window.buildRoute;window.buildRoute=async()=>{if(S.route.length<2)return toast('Добавьте минимум 2 точки');const b=document.getElementById('btn-build');if(b)b.disabled=true;try{const d=await apiFetch('/route/build',{method:'POST',body:JSON.stringify({poi_ids:S.route.map(p=>p.id),optimize:true})});if(window.showRouteModal)window.showRouteModal(d);else window.openRouteLink(d.google_maps_url)}catch(e){toast(e.message||'Не удалось построить маршрут')}finally{if(b)b.disabled=false}};
  styles();
})();