import {state} from '../core/state.js';import {request} from '../core/api.js';import {$,esc,toast} from '../ui/helpers.js';
let active=null;
export async function loadGroups(){const b=$('#groups-list');if(!b)return;b.innerHTML='<div class="jarvis-loading">Загрузка…</div>';try{const gs=await request('/groups');b.innerHTML=gs.length?gs.map(g=>`<button class="card" type="button" data-action="group-open" data-id="${g.id}"><b>${esc(g.name)}</b><span>${esc(g.trip_start||'Дата не задана')}</span></button>`).join(''):'<div class="empty">Групп пока нет</div>';}catch(e){b.innerHTML=`<div class="empty">${esc(e.message)}</div>`;}}
export async function openGroup(id){try{active=await request(`/groups/${id}`);$('#group-title').textContent=active.name;$('#group-date').value=active.trip_start||'';$('#group-members').innerHTML=active.members.map(m=>`<span>@${esc(m.username||m.user_id)} ${m.role==='owner'?'👑':''}</span>`).join('');await refreshGroup();goGroup();}catch(e){toast(e.message)}}
function goGroup(){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$('#group')?.classList.add('active');}
async function refreshGroup(){if(!active)return;const [m,p]=await Promise.all([request(`/groups/${active.id}/messages`),request(`/groups/${active.id}/proposals`)]);$('#group-chat').innerHTML=(m.messages||[]).map(x=>`<div><b>@${esc(x.username||x.author_id)}</b> ${esc(x.text)}</div>`).join('')||'<div class="empty">Чат пуст</div>';$('#group-proposals').innerHTML=(p.proposals||[]).map(x=>`<div><b>${esc(x.name)}</b> — ${x.votes} <button type="button" data-action="group-vote" data-place="${esc(x.place_id)}">👍</button></div>`).join('')||'<div class="empty">Нет предложений</div>';}
export async function createGroup(){const name=prompt('Название группы');if(!name?.trim())return;const d=await request('/groups',{method:'POST',body:JSON.stringify({name:name.trim(),trip_start:$('#group-date')?.value||null})});await loadGroups();await openGroup(d.id);}
export async function invite(){if(!active)return;const username=prompt('Username, например @example_123');if(!username)return;try{const d=await request(`/groups/${active.id}/invite`,{method:'POST',body:JSON.stringify({username})});toast(`Приглашение для ${d.username}: ${d.telegram_url}`)}catch(e){toast(e.message)}}
export async function send(){if(!active)return;const i=$('#group-message'),text=i.value.trim();if(!text)return;await request(`/groups/${active.id}/messages`,{method:'POST',body:JSON.stringify({text})});i.value='';await refreshGroup();}
export async function vote(place_id){if(!active)return;try{await request(`/groups/${active.id}/vote`,{method:'POST',body:JSON.stringify({place_id})});await refreshGroup()}catch(e){toast(e.message)}}
export async function toggleVoting(){if(!active)return;try{await request(`/groups/${active.id}/voting`,{method:'POST'});await refreshGroup()}catch(e){toast(e.message)}}
